### ISSUE TITLE
Cannot use the right click context menu to edit loadouts of units pre-placed into Zeus missions from 3DEN when playing the mission on a dedicated server unless unit is remote controlled first.

### ISSUE THREAD

**Issue by Qerbas** [zen-mod/ZEN#497]
**Arma 3 Version:** `2.00.146773` (stable)
**CBA Version:** `v3.15.2.201119` (stable)
**ZEN Version:** `1.9.0` (stable)

**Mods:**
```
- CBA_A3
- ZEN
```

**Description:**
- You cannot use the right click context menu to edit loadouts of units pre-placed into Zeus missions from 3DEN when playing the mission on a dedicated server unless unit is remote controlled first.  Units placed with the Zeus interface during the mission can have their loadout edited normally.

**Steps to reproduce:**
1. Load my test mission on a dedicated server
2. Try to edit the loadout of the unit that's pre-placed using the right click context menu and notice that the arsenal does not open.
3. Remote control the unit
4. Notice how you can now edit their loadout

**Where did the issue occur?**
- Dedicated

**Additional information:**
Test mission: [Zen_Test.Altis.zip](https://github.com/zen-mod/ZEN/files/4453083/Zen_Test.Altis.zip)

Recording of issue: https://www.youtube.com/watch?v=j59nQY5u29c

**Comment by neilzar** [comment]
Are you running with or without ACE? I can't reproduce the issue with just CBA and ZEN loaded, running on dev, stable and profiling branches. I am running the latest master branch of ZEN, so it may have been fixed already through fixing another issue.

**Comment by Qerbas** [comment]
No, I am running only with CBA_A3 and ZEN on both the server and the client.  I just tried version 1.10 and the issue still persists.  You must be testing on a local host, since I just reconfirmed that you _can_ access the arsenal with a local host, but not when the mission is loaded on a dedicated server.  Please try on a dedicated server.  I can't see any reason why no one else can reproduce this, I've isolated all necessary variables and I've often seen mods/scripts work fine on a local host/single player, but break on a dedicated server, which is exactly what's happening here.
